extern Gfx DL_ttm_geo_000D14_0x702a9c0[];
const GeoLayout star_road_sun_geo[]= {
GEO_CULLING_RADIUS(1000),
GEO_OPEN_NODE(),
GEO_BILLBOARD_WITH_PARAMS(0,0,0,0),
GEO_OPEN_NODE(),
GEO_SCALE(0,32768),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(LAYER_ALPHA,DL_ttm_geo_000D14_0x702a9c0),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};

extern Gfx DL_ttm_geo_000D4C_0x702aaa8[];
const GeoLayout star_road_yoshi_coin_geo[]= {
GEO_CULLING_RADIUS(1000),
GEO_OPEN_NODE(),
GEO_BILLBOARD_WITH_PARAMS(0,0,0,0),
GEO_OPEN_NODE(),
GEO_SCALE(0,32768),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(LAYER_ALPHA,DL_ttm_geo_000D4C_0x702aaa8),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
