const GeoLayout star_road_vc_light[]= {
GEO_CULLING_RADIUS(1500),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(LAYER_TRANSPARENT,DL_rr_geo_000958_0x701bf50),
GEO_CLOSE_NODE(),
GEO_END(),
};

const GeoLayout star_road_vc_cog[]= {
GEO_CULLING_RADIUS(1500),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(LAYER_OPAQUE,DL_rr_geo_0007E8_0x7016570),
GEO_CLOSE_NODE(),
GEO_END(),
};
